# API server configuration
[api]
address = "0.0.0.0"  # Bind to all interfaces in Docker
port = 3000

# Database configuration
[api.database]
url = "postgres://postgres:postgres@db:5432/spore_db"
max_connections = 10 