[websocket]
url = "ws://localhost"  # WebSocket URL for CKB node
reconnect_interval = 5000    # milliseconds
ping_interval = 30000        # milliseconds

[ckb]
type_script_code_hash = "0x4a4dce1df3dffff7f8b2cd7dff7303df3b6150c9788cb75dcf6747247132b9f5"  # Example code hash (TYPE_ID)
type_script_hash_type = "data1"     # Can be "type" or "data1"
query_limit = 300                   # Number of cells to fetch per query 
query_interval_secs = 10            # Number of seconds to wait between queries

# Spore filter configurations
[[spore_filters]]
name = "Default Cluster Filter"      # Name of this filter for identification
enabled = true                       # Whether this filter is active
filter_by_cluster = true             # Filter cells by cluster ID
cluster_id = "0x97dd2076edcb737cc0263a40744efa512c82ed54be9c1105c1c11f7603aae638"  # Cluster ID to filter by
filter_by_type_ids = false           # Filter cells by their Type ID
type_ids = []                        # List of Type IDs to filter by (empty means no filtering)
type_ids_file = ""                   # Optional path to a file containing Type IDs (one per line)
skip_decoding = false                # Skip decoding the cell data (useful for just collecting Type IDs)

[[spore_filters]]
name = "Nervape Collection Filter"      
enabled = true                      
filter_by_cluster = false            
cluster_id = ""                      
filter_by_type_ids = true
type_ids = []                        # No inline Type IDs, all from JSON file
type_ids_file = "config/NervapeInfo.json" # JSON file with Type IDs from typeInfo.args
skip_decoding = true